### ISSUE TITLE
error running with newest version of scrapy

### ISSUE THREAD

**Issue by TruckBC** [kaushikthedeveloper/Goodreads-Giveaway-BOT#3] opened 2017-09-17 04:44 UTC
error received is 

crawl: error: running 'scrapy crawl' with more than one spider is no longer supported

once you delete the password="xxxxxxx" spider, it runs, but fails to sign in as password is not there

**Comment by kaushikthedeveloper** [comment] 2017-09-27 16:33
Hello @petkoganachev , sorry for the late reply.

Could you provide the details of `pip freeze` (version of Scrapy) and the exact `command` that you ran for starting the `Spider`.

**Comment by kaushikthedeveloper** [comment] 2017-10-10 10:06
Since have not received further response from the OP, am **closing** the issue. 

I have been able to **reproduce your error** by giving space between the `arg=` and its argument. 

Ex : `$ scrapy crawl giveaway -a username=  "email_id" -a password= "pass"` 

Note the space between `username=` and `email_id`, `password=` and `pass`

Should be : `$ scrapy crawl giveaway -a username="email_id" -a password="pass"`

For further reference , go through [How to pass multiple arguments to Scrapy spider (getting error running 'scrapy crawl' with more than one spider is no longer supported)?](https://stackoverflow.com/questions/30997024/how-to-pass-multiple-arguments-to-scrapy-spider-getting-error-running-scrapy-c) .

**Closed as completed** 2017-10-10 10:07 UTC
